### ISSUE TITLE
RNifti Memory Usage

### ISSUE THREAD

**Issue by ahmedhumza94** [jonclayden/RNifti#14]
I am using RNifti to read in 4-D .nii files. I am trying to troubleshoot memory usage during read in.

Using R 3.5.2, Ubuntu 16.04.6, and RNifti_0.10.0 I read in a single precision (dim: 182x218x182x142) .nii file using readNifti with internal = FALSE

The workspace reports an object size of 8.203093528 gb. However the R process itself uses about 12.1gb of memory. 

When reading in the file with internal = FALSE, the R process looks to use about 4.673504gb of memory. 

When defining a regular double precision R array of the same dimensions the R process looks to use 8.70244gb of memory.

Running gc() after read in does not seem to free much memory. It also seems that the extra memory used by the R process tends to increase if I increase the number of volumes in the file.

Let me know if you have any suggestions or insights into this issue.

**Comment by jonclayden** [comment]
Hi Humza. The reason for this is that the voxel data potentially exists in two places: in the R array itself and within the internal `nifti_image` C structure. For your single-precision floating-point image with about 1bn elements, the "native" data size in the C struct is roughly 4 GiB, while the R array uses 8 GiB because it uses double precision. When you use `readNifti(..., internal=TRUE)` the resulting object has only the C struct, but with `readNifti(..., internal=FALSE)` the object has **both** the C struct and the R array, for a total of 12 GiB. This is to ensure that subsequent `niftilib` functions called on the internal image produce results that are fully consistent with what would have happened if R hadn't been in the loop.

If you want to keep only the array, you can remove the image's `.nifti_image_ptr` attribute by hand (and then wait for, or force, garbage collection). Bear in mind, however, that this will also lose most of the metadata associated with the image, so you should extract and save that separately (e.g. with `niftiHeader()`) if you need it. I hope this is helpful.

**Comment by ahmedhumza94** [comment]
Thanks for the clarification.

From,

Humza

**Comment by jonclayden** [comment]
No problem. You may be interested to know that I'm currently working on direct indexing into internal images for the next release of the package, which should provide a new, memory-efficient option for accessing the voxel data (or parts of it).
