### ISSUE TITLE
Possible to get dimensions of a nifti file without fully reading it?

### ISSUE THREAD

**Issue by damondpham** [jonclayden/RNifti#19]
Hello! Is it possible to obtain the dimensions of a nifti file without fully loading it into memory? Due to memory limits, I am trying to load and process a 4D bold volume time-series in chunks of time ([,,,1:20], [,,,21:40], etc.). However, this is difficult without knowing the total number of time points. 

I am guessing it might be possible, since readNifti('my_file.nii.gz', volumes=0) yields an error saying
`** volume index -1 (#0) is out of range [0,number_of_volumes]`

**Comment by jonclayden** [comment]
Hi Damon. Yes, certainly – you can get this information from the `dim` element of the header, viz. `niftiHeader("my_file.nii.gz")$dim`. Note that this element uses the NIfTI-1 dimension field convention, so it will always have eight elements, the first of which tells you the dimensionality of the image, with the remainder giving the size in each dimension. So, for example, a value of

```
[1]  3 96 96 60  1  1  1  1
```

means that this is a 3D image of dimension 96 x 96 x 60 voxels. If you just want to know the number of volumes in the time dimension, `niftiHeader("my_file.nii.gz")$dim[5]` should give you that.

By the way, the `volumes` argument to `readNifti` follows R's usual 1-based indexing convention, so the first volume is number 1, not 0. That's why you get the range error there.

**Comment by damondpham** [comment]
Thank you!!
