### ISSUE TITLE
./configure does not generate Makefile

### ISSUE THREAD

**Issue by ToruHironaka** [jonclayden/RNifti#24]
./configure --help show below message, but /confgure did not generate Makefile. My OS is Ubuntu 20.04. Why does not generate Makefile?

By default, `make install' will install all the files in
`/usr/local/bin', `/usr/local/lib' etc.  You can specify
an installation prefix other than `/usr/local' using `--prefix',
for instance `--prefix=$HOME'.

**Comment by muschellij2** [comment]
This should not be run as is.  This is an R package so in R, please run:
```r
install.package("RNifti")
```
or
```r
remotes::install_github("jonclayden/RNifti")
```

**Comment by jonclayden** [comment]
Yes, indeed, the `configure` file at the root of this repo is really only for use with R – its output is `src/Makevars`. Please see the [`standalone` directory](https://github.com/jonclayden/RNifti/tree/master/standalone) for more information on standalone use of `RNifti` outside of R. It contains a basic Makefile.

**Comment by jonclayden** [comment]
1. Yes. There's documentation at <http://doxygen.flakery.org/RNifti/>.
2. No, because for non-R use it is API-only. The standalone binaries are only for demonstration, and don't do anything very interesting, so you probably wouldn't want to install them anywhere.
3. Yes, correct.
4. In which sense? If you mean the NIfTI-1 or NIfTI-2 based versions then the answer is both, but with some adaptions to make them play nicely together.

**Comment by ToruHironaka** [comment]
I meant #4 the latest version of both Nifti-1 or Nifit-2. I think github is the lastest. That was what I meant. 
I looked at your standalone example and I almost understood how it works. But, I need to confirm with you about one last thing. Do I have to have below symbolic link paths for your C API? I thnk your C API needs to compile with your nifiti source codes (RNifti/include/ and RNifti/src) into object files with below specifi link paths. 

niftilib  RNifti  RNifti.h  zlib  znzli

**Comment by jonclayden** [comment]
It may not be quite in sync with the latest version from the niftilib GitHub repo because I modify it slightly, but it's based on a fairly recent version. (niftilib isn't under heavy development though – it's quite stable.) I've also contributed [some patches](https://github.com/NIFTI-Imaging/nifti_clib/pull/124) back to the upstream project.

The `RNifti` C++ API builds on and works alongside the niftilib C API, so yes, you need to link in niftilib and znzlib. They don't have to be symlinked of course – you can copy them into your project – but if you want to change the file hierarchy you'll need to modify your compilation flags or the appropriate `#include` directives. They are included with `RNifti` because they're not typically installed on systems. The system zlib can certainly be used, though, as it is with the R package.

**Comment by ToruHironaka** [comment]
Thanks Jon, "They don't have to be symlinked of course – you can copy them into your project – but if you want to change the file hierarchy you'll need to modify your compilation flags or the appropriate #include directives." <-- this is what I want to confirm. 

I copied RNifit's inst and src directories to /opt/RNifti and set static symbolic links for niftilib RNifti RNifti.h zlib znzli for my RNifti C program directory. This is a quick solution for not worried about file hierachy changes. I only need to copied niftilib RNifti RNifti.h zlib znzli into new project directory, and I can program and compile my RNifti C program. It worked. 

Finally, I would like to thank you for your quick responses and answers, your supports saved my time!
