### ISSUE TITLE
How may I change pixel dimension to fit size?

### ISSUE THREAD

**Issue by zh-zhang1984** [jonclayden/RNifti#27]
I have the following code but the chest CT seems compressed. Any hints for this error? 

```
library(oro.nifti)
library(ggBrain)
library(RNifti)

chestImage = readNIfTI("/Users/zhangzhongheng/Documents/2022/ChestCT_Zhejiang/CTclean/17171437.nii.gz")
chestImage
NIfTI-1 format
  Type            : nifti
  Data Type       : 4 (INT16)
  Bits per Pixel  : 16
  Slice Code      : 0 (Unknown)
  Intent Code     : 0 (None)
  Qform Code      : 1 (Scanner_Anat)
  Sform Code      : 1 (Scanner_Anat)
  Dimension       : 512 x 512 x 140
  Pixel Dimension : 0.74 x 0.74 x 2
  Voxel Units     : mm
  Time Units      : Unknown
#now add aethetic changes with conventional ggplot code.
ggBrain(brains=chestImage,mar=1:3,mar_ind=c(250,250,80),
        row_ind=    c(1,2,1),
        col_ind=    c(2,1,1),
        type='structural',tri_planar=TRUE, lines_color='black',
        fix_ratio = F) +
  scale_fill_continuous(low="black", high="white") + 
  theme_black_bg()
```
The ratio of width and heigth are incorrect.

**Comment by jonclayden** [comment]
Hi! Are you able to share the image file so that I can replicate the issue locally?

**Comment by zh-zhang1984** [comment]
see enclosed the original file;
Thank you [https://res-geo.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png] 17171437.nii.gz<https://1drv.ms/u/s!AnooFyHsUDdzghgzFC4Yj1_uIG-F>
________________________________

**Comment by jonclayden** [comment]
Is `ggBrain()` your own wrapper function? Its arguments don't seem to match `ggbrain::ggbrain()`.

**Comment by jonclayden** [comment]
Please ignore that previous comment – I didn't realise there were two packages whose names differ only in the capitalisation of the 'B'! I've now installed `ggBrain` from GitHub and I can run your code.

But I don't think this issue is anything to do with `RNifti`. You're using `readNIfTI()` (from `oro.nifti`) to load the image, and then `ggBrain` to display it. I'm not sure what the source of the problem, but the roughly equivalent `RNifti` code

```r
library(RNifti)
view(lyr("17171437.nii.gz", min=-1000, max=2000), point=c(250,250,80), interactive=FALSE)
```

appears to generate a quite reasonable-looking image.

Is there a reason to believe that `RNifti` is the ultimate source of your problem?

**Comment by zh-zhang1984** [comment]
yes, the view() function works fine for me; I think it is the problem of ggBrain.
