### ISSUE TITLE
image.data().size() is not equal to size from image.getData<T>.begin() to image.getData<T>.end() ?

### ISSUE THREAD

**Issue by FlouhoShaw** [jonclayden/RNifti#29]
I am using some C++ codes like this to come to the conclusion:

```C++
RNifti::NiftiImage image(path, DT_FLOAT64); 
std::cout << "image.data().size() = " << image.data().size() << std::endl; 
std::vector<float> idata; 
idata = std::vector<float>(image.getData<float>().begin(), image.getData<float>().end()); 
std::cout << "idata.size() = " <<idata.size() << std::endl; 
```

but the std::cout is:

_image.data().size() = 22282240
idata.size() = 44565504_

and dim info from the header is:
dim[8]         = 3 85 512 512 1 1 1 1

**Comment by FlouhoShaw** [comment]
```C++

RNifti::NiftiImage image(path, DT_FLOAT64); 
std::cout << "image.data().size() = " << image.data().size() << std::endl; 
std::vector<double> idata; 
idata = std::vector<double>(image.getData<double>().begin(), image.getData<double>().end()); 
std::cout << "idata.size() = " <<idata.size() << std::endl; 

```

the std::cout is:

_image.data().size() = 22282240
this->idata.size() = 44564992_

**Comment by jonclayden** [comment]
Thanks for the report. Are you able to share the image you're using for this example?

**Comment by jonclayden** [comment]
Actually, I think I see what's going on here, and I think it's down to a mistaken assumption.

    RNifti::NiftiImage image(path, DT_FLOAT64);

This line is misleading because there is no constructor taking a path and datatype. It happens to work because the integer constant is dropped down to `bool`, but it's equivalent to just `RNifti::NiftiImage image(path)`.

    std::cout << "image.data().size() = " << image.data().size() << std::endl;

This is fine, and gives the right answer (85 * 512 * 512 = 22,282,240).

    std::vector<double> idata; 
    idata = std::vector<double>(image.getData<double>().begin(), image.getData<double>().end());

This is the problem. The `getData()` method (which is now deprecated) returns by value, not reference, so the results of your two calls to `image.getData<double>()` are *two separate copies* of the data. You then create a third copy that spans from the beginning of one copy to the end of the other. If they happen to have been given contiguous chunks of memory this will combine the copies into a new vector of twice the length (hence the doubled size you see), but this is surely not what you mean to do, is completely unsafe and can easily lead to a crash. If you simply do

    std::vector<double> idata = image.getData<double>();

you get the right answer of the right length, but I would suggest using `data()` instead.

**Comment by FlouhoShaw** [comment]
thank you for your patiance, problems already solved !
