### ISSUE TITLE
Nifti file to c++ vector

### ISSUE THREAD

**Issue by Girish-Anadv-07** [jonclayden/RNifti#33]
I need to get nifti file data to a vector I used this code
```
RNifti::NiftiImage image("../../example.nii.gz");
vector<float> data = image.getData();
```
But I get errors 
```
../../3d_out.cpp:175:32: error: no matching member function for call to 'getData'
    vector<float> data = image.getData();
                         ~~~~~~^~~~~~~
./RNifti/NiftiImage_impl.h:1722:44: note: candidate template ignored: couldn't infer template argument 'TargetType'
inline std::vector<TargetType> NiftiImage::getData (const bool useSlope) const
                                           ^
1 error generated.
```
Is this the right way to do it?

**Comment by jonclayden** [comment]
As the error says, the template argument isn't inferred, so you need to specify it explicitly, viz.

```cpp
vector<float> data = image.getData<float>();
```

The `getData()` method is deprecated, though, so the preferred route is now to use `data()`:

```cpp
RNifti::NiftiImageData niidata = image.data();
vector<float> data(niidata.begin(), niidata.end());
```

**Comment by Girish-Anadv-07** [comment]
It worked thank you so much. But I need help with converting a vector to nii file.
```
    af::array convolved = convolve3d(signal, filter, strides, padding, dilation, filter_dims);
    af_print(convolved);
    vector<float> conv(256*256*256);
    convolved.host(conv.data());
    conv.toFile("test.nii.gz", "auto");
```
I get error 
```
error: no member named 'toFile' in 'std::vector<float>'
    conv.toFile("test.nii.gz", "auto");
    ~~~~ ^
1 error generated.
```
I recognize the error but I don't know the right way to use the toFile() function.

**Comment by jonclayden** [comment]
You're calling the `toFile()` method on a `vector`, not a `NiftiImage`. You need to convert to the latter first:

```cpp
RNifti::NiftiImage image({256, 256, 256}, DT_FLOAT32);
image.replaceData(conv, DT_FLOAT32);
image.toFile("test.nii.gz");
```

**Comment by Girish-Anadv-07** [comment]
It worked. 
I need to release the image pointer manually by myself.
```
    RNifti::NiftiImage image("../../t1_c.nii.gz");
    RNifti::NiftiImageData niidata = image.data();
    image.release();
```
Error:
```
../../3d_out.cpp:173:11: error: 'release' is a protected member of 'RNifti::NiftiImage'
    image.release();
          ^
./RNifti/NiftiImage.h:1298:10: note: declared protected here
    void release ();
         ^
1 error generated.

```

**Comment by Girish-Anadv-07** [comment]
Also, How can I keep the output Header the same as the input header?

**Comment by jonclayden** [comment]
> I need to release the image pointer manually by myself.

Since a `NiftiImage` object can be treated as a pointer to a `nifti_image` struct, it's semantically valid to free it with `nifti_image_free(image)`, but I would *strongly* advise against it. Unless you are very careful you will double-free the memory, and probably get a segmentation fault. The release will happen automatically when the `image` object goes out of scope, so manually freeing it shouldn't be necessary, but if you think `NiftiImage`'s memory management won't work for you then do let me know why not.

> Also, How can I keep the output Header the same as the input header?

I assume you mean you want to preserve the NIfTI header from the source file? When you copy an image the header should go along with it – or you can just reuse the container. So a full read-process-write cycle could look like

```cpp
RNifti::NiftiImage image("../../example.nii.gz");
RNifti::NiftiImageData niidata = image.data();

vector<float> data(niidata.begin(), niidata.end());
// Do some work on the "data" vector, transforming it in place
image.replaceData(data, DT_FLOAT32);

image.toFile("output.nii.gz")
```

And in fact, conversion to and from `std::vector` (the middle block) may not be necessary, as you may be able to make use of `NiftiImageData`'s iterators, as in `std::transform(niidata.begin(), niidata.end(), niidata.begin(), <function>)`.
