### ISSUE TITLE
Viewing two niftis with different color schemes

### ISSUE THREAD

**Issue by butellyn** [jonclayden/RNifti#36]
Hello! I would like to view an amygdala mask on top of its corresponding MNI space. I tried `view(amyg, mni)` first (where `amyg` and `mni` are objects I loaded using `readNifti()`), but was not able to easily see the mask due to the fact that both were on a grey scale. I tried `view(lyr(amyg, scale = 'blue'), mni)` next, but got the following error: 

Error in shades::gradient(scale, 100) : 
  A single-element argument should specify a predefined colour map

I tried a few different colors, but none worked. Would it be possible to add documentation about how to view niftis with different color schemes? Or if this already exists, could you point me to it? Thank you!

**Comment by jonclayden** [comment]
Hi Ellyn, and thanks for raising this. Admittedly the function documentation and the error text could be clearer on this, although `?lyr` does specify for the `scale` argument that

> A fixed colour can be used by wrapping a string in a call to `I`.

(This is borrowing an idiom from `base` whereby `I(...)` indicates that the argument should be taken "as-is", in this case rather than interpreting it as the name of a predefined scale.)

Note also that the first layer specified is plotted first, so it appears on the bottom. I think you probably want

```r
view(mni, lyr(amyg, scale = I('blue')))
```

but please do let me know whether or not this works as you intend!

**Comment by butellyn** [comment]
Amazing! This worked. Thank you.
